kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: lvopensearch
  namespace: opensearch
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - http:
        paths:
          - path: /opensearch
            pathType: Prefix
            backend:
              service:
                name: opensearch
                port:
                  number: 9200