kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: lvopensearch
  namespace: opensearch
  annotations:
    # spec.ingressClassName: traefik # This was an incorrect placement for ingressClassName
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: opensearch-stripprefix-elastic@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: kube.local
      http:
        paths:
          - path: /opensearch
            pathType: Prefix
            backend:
              service:
                name: opensearch
                port:
                  number: 9200