apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lvopensearch
  namespace: opensearch
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kube.local`) && (PathPrefix(`/opensearch`))
      kind: Rule
      services:
      - name: lvopensearch-cluster-masters
        port: 9200
        namespace: opensearch