apiVersion: opensearch.org/v1
kind: OpenSearchISMPolicy
metadata:
   name: sample-policy
spec:
   opensearchCluster:
      name: opensearch
   description: Sample policy
   policyId: sample-delete-policy
   default_state: hot
   states:
      - name: hot
         actions: 
            - replica_count:
               number_of_replicas: 4
         transitions:
            - state_name: delete
              conditions:
                  min_index_age: "10d"
      - name: delete
         actions:
            - delete: {}
         transitions: []