kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: lvopensearch-dashboards
  namespace: opensearch
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - http:
        paths:
          - path: /kibana
            pathType: Prefix
            backend:
              service:
                name: opensearch-dashboards
                port:
                  number: 5601