kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: lvopensearch-dashboards
  namespace: opensearch
  annotations:
    # spec.ingressClassName: traefik # This was an incorrect placement for ingressClassName
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: kube.local
      http:
        paths:
          - path: /kibana
            pathType: Prefix
            backend:
              service:
                name: opensearch-dashboards
                port:
                  number: 5601