apiVersion: opensearch.opster.io/v1
kind: OpensearchIndexTemplate
metadata:
  name: otel-v1-apm-service-map-template
  namespace: opensearch
spec:
  opensearchCluster:
    name: opensearch

  name: otel-v1-apm-service-map-template # name of the index template - defaults to metadata.name. Can't be updated in-place

  indexPatterns: # required index patterns
    - "otel-v1-apm-service-map*"
  composedOf: # optional
    - simple-opensearch-component-template
