apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: data-prepper
  name: data-prepper-config
data:
  pipelines.yaml:  |
    entry-pipeline:
      source:
        otel_trace_source:
          ssl: false
          authentication:
            unauthenticated: {}
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      sink:
        - pipeline:
            name: "raw-trace-pipeline"
        - pipeline:
            name: "service-map-pipeline"

    raw-trace-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      processor:
        - otel_trace_raw: {}
        - otel_trace_group: {} # Removed invalid 'hosts' parameter
      sink:
        - opensearch:
            hosts: ["http://opensearch-masters.opensearch.svc.cluster.local:9200"]
            insecure: true
            index_type: trace-analytics-raw

    service-map-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      processor:
        - service_map_stateful: {}
      sink:
        - opensearch:
            hosts: ["http://opensearch-masters.opensearch.svc.cluster.local:9200"]
            insecure: true
            index_type: trace-analytics-service-map

    logs-pipeline:
      source:
        otel_log_source:
          # This source listens for OTLP log data.
          # It shares the OTLP server with otel_trace_source, typically on port 21890 (gRPC) / 21891 (HTTP) when ssl is false.
          # Your OTel Collector is configured to send logs to port 21890.
          ssl: false
          authentication:
            unauthenticated: {} # Matches OTel collector exporter which sends unauthenticated requests
      buffer:
        bounded_blocking:
          buffer_size: 10240 # Maximum number of records the buffer can hold
          batch_size: 256    # Number of records to send to the sink in a single batch
      processor:
        - otel_logs: {} # Standard processor for OTLP logs, prepares them for sinks
      sink:
        - opensearch:
            hosts: ["http://opensearch-masters.opensearch.svc.cluster.local:9200"]
            insecure: true # Set to false if OpenSearch uses TLS and you configure Data Prepper's sink for TLS
            index: "otel-logs-%{yyyy.MM.dd}" # Dynamic index name based on date, e.g., otel-logs-2023.10.27
            # Optional: Define an OpenSearch index template for better control over mappings and settings for your log indices.
            # template_file: "/usr/share/data-prepper/pipelines/opensearch_log_template.json"
            # document_id_field: "traceId" # If you want to use a field from the log as the document ID
            # routing_field: "service.name" # If you want to route documents to specific shards based on a field

# The EOF marker from the original snippet is not part of the YAML content.