apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: opensearch-privileged-exception
  namespace: opensearch
spec:
  exceptions:
    - policyName: disallow-privileged-containers
      ruleNames:
        - privileged-containers
        - autogen-privileged-containers
  match:
    any:
      - resources:
          kinds:
            - Pod
            - StatefulSet
          namespaces:
            - opensearch