apiVersion: opensearch.opster.io/v1
kind: OpensearchComponentTemplate
metadata:
  name: simple-opensearch-component-template
  namespace: opensearch
spec:
  opensearchCluster:
    name: opensearch # required, name of the OpenSearch cluster

  template: # required
    aliases: # optional
      my_alias: {}
    settings: # optional
      number_of_shards: 2
      number_of_replicas: 1
    mappings: # optional
      properties:
        timestamp:
          type: date
          format: yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis
        value:
          type: double
  version: 1 # optional
 