opensearch-cluster:
  # OpenSearchCluster configuration
  cluster:
    # -- OpenSearchCluster name, by default release name is used
    name: "opensearch"
    general:
      serviceName: "opensearch"
      version: 2.3.0
    dashboards:
      enable: true
      basePath: "/kibana"
      version: 2.3.0
      replicas: 2
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      tls:
        enable: false
      opensearchCredentialsSecret:
        name: "opensearch-admin-password"