opensearch:
  clusterName: "opensearch-cluster"
  singleNode: true
  extraEnvs: 
  - name: "OPENSEARCH_INITIAL_ADMIN_PASSWORD"
    value: "VerySecurePassword12!"
opensearch-dashboards:
  plugins:
    enabled: false
  config:
    dynamic:
      authc:
        basic_internal_auth_domain:
          description: "Authenticate using HTTP basic against the internal users database"
          http_enabled: true
          transport_enabled: true
          order: 1
          http_authenticator:
            type: basic
            challenge: true
          authentication_backend:
            type: internal