# OpenSearchCluster configuration
cluster:
  # -- OpenSearchCluster name, by default release name is used
  name: "lvopensearch"
  general:
    serviceName: lvopensearch
    version: 2.3.0
    additionalConfig:
      plugins.security.ssl.transport.enforce_hostname_verification: false
  dashboards:
    enable: true
    basePath: "/kibana"
    version: 2.3.0
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
    tls:
      enable: false
    opensearchCredentialsSecret:
      name: opensearch-admin-password
    additionalConfig:
      # https://opensearch.org/docs/latest/install-and-configure/install-dashboards/tls/
      opensearch.ssl.verificationMode: none
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "5Gi"
      nodeSelector:
      resources:
         requests:
            memory: "512Mi"
            cpu: "200m"
         limits:
            memory: "512Mi"
            cpu: "200m"
      roles:
        - "cluster_manager"
        - "data"