opensearch:
  clusterName: "opensearch-cluster"
  singleNode: true
  extraEnvs: 
  - name: "OPENSEARCH_INITIAL_ADMIN_PASSWORD"
    value: "VerySecurePassword12!"
opensearch-dashboards:
  plugins:
    enabled: false
  extraEnvs: 
  - name: "OPENSEARCH_INITIAL_ADMIN_PASSWORD"
    value: "VerySecurePassword12!"