opensearch-cluster:
  # OpenSearchCluster configuration
  cluster:
    # -- OpenSearchCluster name, by default release name is used
    name: "opensearch"
    general:
      serviceName: "opensearch"
      version: 2.3.0
    dashboards:
      enable: true
      basePath: "/kibana"
      version: 2.3.0
      replicas: 1
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      tls:
        enable: false
      opensearchCredentialsSecret:
        name: "opensearch-admin-password"
    nodePools:
    - component: masters
      diskSize: "5Gi"
      replicas: 3
      roles:
        - "master"
        - "data"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"

data-prepper:
  # Tells the data-prepper sub-chart to use an existing ConfigMap
  # for its pipeline configurations.
  config:
  # -- Main Data Prepper configuration file content
  data-prepper-config.yaml: |
    entry-pipeline:
      delay: "100"
      source:
        otel_trace_source:
          ssl: false
          authentication:
            unauthenticated:
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      sink:
        - pipeline:
            name: "raw-trace-pipeline"
        - pipeline:
            name: "service-map-pipeline"

    raw-trace-pipeline:
      delay: "100"
      source:
        pipeline:
          name: "entry-pipeline"
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      processor:
        - otel_traces: 
      sink:
        - opensearch:
            hosts: ["http://opensearch-masters.opensearch.svc.cluster.local:9200"]
            insecure: true
            index_type: trace-analytics-raw

    service-map-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      processor:
        - service_map:
      sink:
        - opensearch:
            hosts: ["http://opensearch-masters.opensearch.svc.cluster.local:9200"]
            insecure: true
            index_type: trace-analytics-service-map

opentelemetry-collector:
  mode: deployment
  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.127.0"
  # This section defines which ports will be opened on the Kubernetes Service
  # created for the OpenTelemetry Collector.
  ports:
    otlp:
      enabled: true
      containerPort: 4317
      servicePort: 4317
      hostPort: 4317
      protocol: TCP
      # nodePort: 30317
      appProtocol: grpc
    otlp-http:
      enabled: true
      containerPort: 4318
      servicePort: 4318
      hostPort: 4318
      protocol: TCP
    zipkin:
      enabled: true
      containerPort: 9411
      servicePort: 9411
      hostPort: 9411
      protocol: TCP
  
  config:
    receivers:
        otlp:
            protocols:
              http:
                  endpoint: 0.0.0.0:4318
                  cors: # Added for explicitness, though defaults might apply
                    allowed_origins:
                        - "*"
                    allowed_headers:
                        - "*"
                    max_age: 7200
        zipkin:
            endpoint: 0.0.0.0:9411

    processors:
        batch/traces:
            timeout: 1s
            send_batch_size: 50

    exporters:
        otlp/data-prepper:
            endpoint: opensearch-data-prepper.opensearch.svc.cluster.local:21890
            tls:
              insecure: true
              insecure_skip_verify: true

    service:
        pipelines:
            traces:
              receivers: [otlp, zipkin]
              processors: [batch/traces]
              exporters: [otlp/data-prepper]
