opensearch:
  clusterName: "opensearch-cluster"
  singleNode: true
  extraEnvs: 
  - name: "OPENSEARCH_INITIAL_ADMIN_PASSWORD"
    value: "some_strong_password_here"
opensearch-dashboards:
  plugins:
    enabled: false