opensearch-cluster:
  # OpenSearchCluster configuration
  cluster:
    # -- OpenSearchCluster name, by default release name is used
    name: "opensearch"
    general:
      serviceName: "opensearch"
      version: 2.19.2
      monitoring:
        enable: false
        labels:
          serviceMonitorSelector: prometheus
          release: prometheus
        tlsConfig:
          insecureSkipVerify: true
    dashboards:
      enable: true
      basePath: "/kibana"
      version: 2.19.2
      replicas: 1
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      tls:
        enable: false
      opensearchCredentialsSecret:
        name: "opensearch-admin-password"
    nodePools:
    - component: masters
      diskSize: "5Gi"
      replicas: 3
      roles:
        - "master"
        - "data"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"

