opensearch-cluster:
  # OpenSearchCluster configuration
  cluster:
    # -- OpenSearchCluster name, by default release name is used
    name: "opensearch"
    general:
      serviceName: "opensearch"
      version: 3.8.0
      vendor: Opensearch
      httpPort: 9200
      setVMMaxMapCount: true
      drainDataNodes: true
      pluginsList: []
      monitoring:
        enable: false
        labels:
          serviceMonitorSelector: prometheus
          release: prometheus
        tlsConfig:
          insecureSkipVerify: true
    dashboards:
      enable: true
      basePath: "/kibana"
      version: 3.8.0
      replicas: 1
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      tls:
        enable: false
      additionalConfig:
        opensearch.ssl.verificationMode: none
      opensearchCredentialsSecret:
        name: "opensearch-admin-password"
    nodePools:
    - component: masters
      diskSize: "5Gi"
      replicas: 3
      roles:
        - "master"
        - "data"
      probes:
        startup:
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 30
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
    security:
      config: {}

monitoring:
  exporter:
    enabled: true
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.9.0
    imagePullPolicy: IfNotPresent
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    opensearch:
      scheme: https
      host: opensearch.opensearch.svc.cluster.local
      port: 9200
      insecureSkipVerify: true
      credentialsSecret:
        name: opensearch-admin-password
        usernameKey: username
        passwordKey: password
    service:
      port: 9114
      targetPort: 9114
    serviceMonitor:
      enabled: true
      namespace: prometheus
      interval: 30s
      scrapeTimeout: 10s
      labels:
        serviceMonitorSelector: prometheus
        release: prometheus
