opensearch-cluster:
  # OpenSearchCluster configuration
  cluster:
    # -- OpenSearchCluster name, by default release name is used
    name: "opensearch"
    general:
      serviceName: "opensearch"
      version: 2.3.0
    dashboards:
      enable: true
      basePath: "/kibana"
      version: 2.3.0
      replicas: 1
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      tls:
        enable: false
      opensearchCredentialsSecret:
        name: "opensearch-admin-password"
    nodePools:
    - component: masters
      diskSize: "5Gi"
      replicas: 3
      roles:
        - "master"
        - "data"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"

data-prepper:
  # Tells the data-prepper sub-chart to use an existing ConfigMap
  # for its pipeline configurations.
  existingConfigmap: "data-prepper-config"

opentelemetry-collector:
  mode: daemonset
  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.127.0"
  # This section defines which ports will be opened on the Kubernetes Service
  # created for the OpenTelemetry Collector.
  ports:
    otlp-grpc: # OTLP gRPC receiver
      enabled: true
      name: otlp-grpc # Name for the service port
      port: 4317      # Port the service will listen on
      protocol: TCP
      # targetPort: 4317 # Port on the pod, defaults to 'port' or resolved by name
      # appProtocol: grpc # Optional: for Kubernetes 1.19+
    otlp: # OTLP HTTP receiver
      enabled: true
      name: otlp # Name for the service port (often 'otlp-http')
      port: 4318   # Port the service will listen on
      protocol: TCP
      # targetPort: 4318
      # appProtocol: http
    zipkin: # Zipkin receiver
      enabled: true
      name: zipkin
      port: 9411
      protocol: TCP
      # targetPort: 9411
  presets:
    logsCollection:
      enabled: true
      includeCollectorLogs: true
  config:
    receivers:
        otlp:
            protocols:
              http:
                  endpoint: 0.0.0.0:4318
                  cors: # Added for explicitness, though defaults might apply
                    allowed_origins:
                        - "*"
                    allowed_headers:
                        - "*"
                    max_age: 7200
              grpc:
                  endpoint: 0.0.0.0:4317
        zipkin:
            endpoint: 0.0.0.0:9411

    processors:
        batch/traces:
            timeout: 1s
            send_batch_size: 50
        batch/logs:
            timeout: 1s
            send_batch_size: 100

    exporters:
        otlp/data-prepper:
            endpoint: opensearch-data-prepper.opensearch.svc.cluster.local:21890
            tls:
              insecure: true

    service:
        pipelines:
            traces:
              receivers: [otlp, zipkin]
              processors: [batch/traces]
              exporters: [otlp/data-prepper]
            logs:
              receivers: [otlp]
              processors: [batch/logs]
              exporters: [otlp/data-prepper]
